services:
  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_DB: sneaky-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Igor2828
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sneaky-store-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - sneaky-store-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sneaky-store-net

networks:
  sneaky-store-net:
    driver: bridge

volumes:
  db-data:
